project:
  type: website
  output-dir: docs

website:
  title: "Muslim Flourishing Study"
  
  page-footer:
    left: |
      <span class="container"><strong>Made with [Posit Quarto on RStudio](https://quarto.org/docs/get-started/hello/rstudio.html){target="_blank"}</strong></span>
    right: |
      <span class="container"><strong>[Project Github Repository](https://github.com/usman-afzali/nzavs-flourishing){target="_blank"}</strong></span>
    background: "#d85e33"
  
  navbar:
    pinned: true
    left:
      - text: "Welcome"
        file: intro.qmd
      - text: "The Team"
        file: team.qmd
      - text: "Project Description"
        file: projectdesc.qmd
      - text: "Reports and Publications"
        file: reports.qmd
      - text: "Data and code"
        file: data-and-code.qmd        
      - text: "Community Partners"
        file: community-partners.qmd  
    right:
      - icon: github
        href: https://github.com/usman-afzali/nzavs-flourishing
    page-navigation: true

format:
  html:
    theme: [united, styles.scss]
    css: styles.scss
    highlight-style: tango

editor: source

